# Generated by Django 3.1.6 on 2021-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="goal",
            field=models.TextField(default=1.0, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="subjectOfInterest",
            field=models.CharField(default=1.0, max_length=100),
        ),
    ]
