# Generated by Django 3.1.6 on 2021-04-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.TextField(default='Default String', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjectOfInterest',
            field=models.CharField(default='Default String', max_length=100),
        ),
    ]
