# Generated by Django 3.1.6 on 2021-05-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210501_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjectOfInterest',
            field=models.CharField(max_length=100),
        ),
    ]
