# Generated by Django 3.1.6 on 2021-08-02 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Math', 'Math'), ('Science', 'Science'), ('History', 'History'), ('Literature', 'Literature'), ('Foreign Language', 'Foreign Language'), ('Geography', 'Geography')], default='Information Technology', max_length=30)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
